---
# This playbook configures a macbook for python development

- name: Configure software on os x
  hosts: local
  sudo: yes
  sudo_user: andermic
  
  vars_files:
    - env_vars/base.yml
  
  roles:
    - devbox